update query records and request to download api
Emotiv/cortex-example pull request #204
Opened 2023-06-25 08:37 UTC by tungntEmotiv

The PR  include:

- to add query_records.py example to demo how to use  queryRecords, requestToDownloadRecordData, and exportRecord api. 
- fix issue directory of certificate file

Please help to review. Thanks

2023-07-03 02:54 UTC, thamha-emotiv approved these changes

2023-07-03 14:54 UTC, nguoithichkhampha requested changes

2023-07-03 14:54 UTC, nguoithichkhampha commented on python/cortex.py
> +        file_dir_path = os.path.dirname(os.path.realpath(__file__))
should use high level package to handle file path 
https://docs.python.org/3/library/pathlib.html

2023-07-03 15:01 UTC, nguoithichkhampha commented on python/cortex.py
> +            elif  key == 'auto_create_session':
we should tell about optional params in readme file..

2023-07-03 15:04 UTC, nguoithichkhampha commented on python/cortex.py
> +        elif req_id == QUERY_RECORDS_ID:
why don't use switch case. it's more readable then a lot of if-else.

2025-08-08 08:08 UTC, tungntEmotiv commented on python/cortex.py
> +            elif  key == 'auto_create_session':
I will add to description of function init in cortex and at query_records.py

2025-08-08 08:38 UTC, tungntEmotiv commented on python/cortex.py
> +        file_dir_path = os.path.dirname(os.path.realpath(__file__))
thank, i will update

2025-08-08 09:19 UTC, tungntEmotiv commented
I have updated rework. please help to review again. Thanks

2025-08-08 10:02 UTC, nguoithichkhampha approved these changes

2025-10-09 03:17 UTC, merged