added option to save data to csv
Emotiv/cortex-example pull request #84
Opened 2020-04-15 10:20 UTC by rockangator

Added the ability save recorded data to csv using pandas. User can opt to save or not, provide location of the saved file and suffix in the name of the file.
pls excuse any mistakes and feel free to mend them, i am fairly new at doing this.

2020-04-20 06:40 UTC, nguoithichkhampha requested changes

2020-04-20 06:40 UTC, nguoithichkhampha commented on python/lib/cortex.py
> +import pandas as pd
Can you implement new feature in other file ? cortex.py should be a basic class

2020-04-20 12:16 UTC, areejhameed commented on python/collect_emotiv_data.py
> +from lib.cortex import Cortex
when i used from  lib.cortex import cortex , an error message "no module called lib could be fined" 
how can i fix it? 
thanks

2020-06-11 01:28 UTC, tanpv reviewed
hi, I do not sure if this is good way to save and export data to csv. Officially, we could create record and then export that record to csv format. Please try to refer to this example
https://github.com/Emotiv/cortex-v2-example/blob/python_example/python/record.py

2020-08-03 01:33 UTC, closed without merging